-- master.chklist_requirement_rule definition
-- Drop table
-- DROP TABLE master.chklist_requirement_rule;

create table master.chklist_requirement_rule ( chk_id uuid default gen_random_uuid() not null,
	chk_cd varchar(50) not null,
	module_code varchar(50) not null,
	requirement_type varchar(30) not null,
	title varchar(255) not null,
	description text null,
	input_schema jsonb null,
	show_if jsonb null,
	inherit_from jsonb null,
	sync_to_parent jsonb null,
	min_responses_required int4 default 1 not null,
	is_mandatory bool default true not null,
	display_order int4 default 0 not null,
	local_vernacular text null,
	is_active bool default true not null,
	entry_ts timestamp(3) default CURRENT_TIMESTAMP not null,
	updt_ts timestamp(3) default CURRENT_TIMESTAMP not null,
	entry_by varchar(50) null,
	updt_by varchar(50) null,
	constraint chklist_requirement_rule_pkey primary key (chk_id),
	constraint chklist_requirement_rule_unq unique (chk_cd,
	description));
-- Permissions

alter table master.chklist_requirement_rule owner to postgres;

grant all on
table master.chklist_requirement_rule to postgres;


INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('fbf83d12-b3fd-441e-b89d-9ad20a98dc65'::uuid,'SCHEDULE_LAND_TABULAR_MOUZA','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Schedule of Land (Tabular & Mouza Abstract - 2 Copies)','Two copies of Schedule of land in tabular form with land type wise and mouza wise abstract','{"columns": ["mouza_name", "plot_no", "tenancy_ha", "govt_ha", "forest_ha", "total_ha"], "control_type": "TABULAR_ABSTRACT", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "abstract_status", "target_entity": "land_schedule", "value_on_verify": "SUBMITTED"}',1,true,30,'भूमि प्रकार-वार और मौजा-वार सारांश के साथ सारणीबद्ध रूप में भूमि की अनुसूची (2 प्रतियां)',true,'2026-08-04 15:31:45.323','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('2219b249-0074-413c-b83a-ac534b775ed2'::uuid,'RECONCILIATION_CERT_FORM_VII','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Reconciliation Certificate (Form VII)','Copy of reconciliation certificate (Form VII) duly signed by competent authority','{"form_fields": [{"name": "form_vii_ref_no", "type": "text", "required": true}], "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "reconciliation_status", "target_entity": "project_proposal", "value_on_verify": "FORM_VII_ATTACHED"}',1,true,40,'समाधान प्रमाण पत्र (फॉर्म VII) की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('2ed0dee6-f8a8-4c9f-b429-8dc0c6c73d76'::uuid,'REVENUE_PLAN_MOUZA_COLOR_WASH','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Revenue Plan with Boundary & Land Type Color Washing','A revenue plan showing boundary of approved project/working area, surface features, land owned by ECL, Govt land, Patta Land, Forest land washed in different colors','{"max_size_mb": 50, "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "has_revenue_plan", "target_entity": "project_proposal", "value_on_verify": true}',1,true,50,'विभिन्न रंगों में दर्शाया गया सीमा और भूमि प्रकार वाला राजस्व मानचित्र',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('145b6b71-b2c2-4fad-a348-bff49e02450d'::uuid,'STATUTORY_CLEARANCES_DGMS','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Statutory Clearances (DGMS, etc.)','Copies of statutory clearances like approval obtained from DGMS etc., if obtained','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,NULL,1,false,70,'डीजीएमएस (DGMS) आदि से प्राप्त वैधानिक मंजुरियों की प्रतियां (यदि प्राप्त हों)',true,'2026-08-04 15:31:45.323','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('dd0295e0-a2a0-40f5-953d-61b16413789d'::uuid,'FOREST_CLEARANCE_STAGE_I_II','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Forest Clearance (Stage-I / Stage-II)','Copy of Forest Clearance, if obtained','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 5, 6], "conditions": [{"field": "land_breakdown.forest_ha", "value": 0, "operator": ">"}]}',NULL,'{"target_field": "forest_clearance_status", "target_entity": "project_proposal", "value_on_verify": "ATTACHED"}',1,false,80,'वन मंजूरी की प्रति (यदि प्राप्त हो)',true,'2026-08-05 17:07:25.484','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('ce719ca6-c590-4d69-93ba-5abce9ba981e'::uuid,'CERT_FIVE_POINT_FORM_XVI','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','FIVE-POINT Certificate in Form XVI','A FIVE-POINT certificate in Form XVI','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XVI", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,NULL,1,true,90,'फॉर्म XVI में पांच-बिंदु (FIVE-POINT) प्रमाण पत्र',true,'2026-08-05 17:07:25.484','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('16b14e3f-55f1-49b7-94b2-0eb8c74c7f7c'::uuid,'STANDARD_CHECKLIST_ECL_2005','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Standard Checklist (ECL Office Orders 2005)','A standard ''Check List'' as circulated through Office Order (Ref. No. ECL/CMD/LRE/ANG/Check-list/1071 Date 25th Nov 2005)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,NULL,1,true,100,'कार्यालय आदेश (ईसीएल/सीएमडी/एलआरई 2005) के माध्यम से परिचालित मानक चेक लिस्ट',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('f9a060bd-1661-4366-9234-b7ab98ef84ba'::uuid,'INVOLVEMENT_EMPLOYMENT_COUNT','LAND_ACQ_PROPOSAL','DATA_FORM','Involvement of Employment Details','Involvement of employment, if any (Specify Number of employment)','{"form_fields": [{"name": "employment_count", "type": "number", "label": "Number of Employments", "required": true}], "control_type": "DATA_FORM"}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"sync_fields": {"employment_count": "user_input.employment_count"}, "target_field": "total_employment_proposed", "target_entity": "project_proposal"}',1,true,110,'रोजगार की भागीदारी (रोजगार की संख्या निर्दिष्ट करें)',true,'2026-08-04 15:31:45.323','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('3e52b0d4-6e14-4899-92f9-4ec4b6e75cbc'::uuid,'TECHNO_ECONOMIC_REPORT_ACQ','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Techno-Economic Report for Land Acquisition','Techno-Economic Report showing estimated total financial involvement and capital involvement for cost land acquisition, rehabilitation and employment for land','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,NULL,1,true,120,'भूमि अधिग्रहण, पुनर्वास और रोजगार की लागत दर्शाने वाली तकनीकी-आर्थिक रिपोर्ट',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('a1aad664-8b0d-4257-886a-d00c1b140d11'::uuid,'REPORT_ALCC_AGM_RECOMMENDATION','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Area Land Cell Committee Report & AGM Recommendation','Report on examination of the proposal by the ''Area Land Cell Committee'' and recommendation thereof & Recommendation of the Area General Manager','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "agm_approval_status", "target_entity": "project_proposal", "value_on_verify": "RECOMMENDED"}',1,true,130,'क्षेत्रीय भूमि सेल समिति की जांच रिपोर्ट और क्षेत्रीय महाप्रबंधक (AGM) की संस्तुति',true,'2026-08-04 15:31:45.323','2026-08-06 12:32:44.187',NULL,'seed');
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('8578019f-2a05-466c-a9dd-cb4c39344ee0'::uuid,'CBA_SEC_4_GAZETTE_NOTIFICATION','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Copy of Gazette Notification under Section 4 (CBA Act)','Copy of Gazette Notification published in Gazette of India under Section 4(1) of CBA (A&D) Act 1957','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,'{"target_field": "cba_sec_4_notified", "target_entity": "project_proposal", "value_on_verify": true}',1,true,140,'सीबीए अधिनियम की धारा 4 के तहत भारत के राजपत्र में प्रकाशित अधिसूचना की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('cc701a0f-cef6-4592-9a14-94040e81c705'::uuid,'CBA_SEC_7_GAZETTE_DRAFT_FORMAT_2D','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Draft Gazette Notification under Section 7(1) (Format 2D)','Proposed draft notification under Section 7(1) of CBA Act in English and Hindi in Format No. 2D','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORMAT_2D", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,150,'धारा 7(1) के तहत प्रस्तावित मसौदा अधिसूचना (प्रारूप 2D में)',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('823a4c28-bbf0-4868-8959-bef19c17f9b4'::uuid,'CBA_SEC_9_GAZETTE_NOTI_APP','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Application & Draft Gazette Notification under Section 9(1)','Application requesting MOC for issue of Gazette notification u/s 9(1) giving details of coal block and copy of Sec 4(1) & 7(1) notifications','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,160,'धारा 9(1) के तहत राजपत्र अधिसूचना जारी करने का आवेदन पत्र और मसौदा',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('b2e73e61-5cb0-4acf-a4b8-02931e74d06c'::uuid,'CBA_SEC_11_GAZETTE_DRAFT_FORMAT_4A','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Draft Gazette Order under Section 11(1) (Format 4A)','A draft order under Section 11(1) of the CBA Act in respect of coal block in English and Hindi in Format No. 4A','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORMAT_4A", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,170,'सीबीए अधिनियम की धारा 11(1) के तहत मसौदा आदेश (प्रारूप 4A में)',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('81eb73e7-22a4-4620-afed-bc5f1c5dc644'::uuid,'CBA_FORMAT_1B_NOT_LEASED_CERT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Certificate Confirming Area Not Leased Out (Format 1B)','Certificate confirming area proposed to be notified has not been leased out to any other party by State/Central Govt (Format No. 1B)','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORMAT_1B", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,180,'प्रमाणपत्र कि प्रस्तावित क्षेत्र किसी अन्य पार्टी को पट्टे पर नहीं दिया गया है (प्रारूप 1B)',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('92f880cf-f460-4abd-a119-d6950e42ea0e'::uuid,'CBA_FORMAT_2A_COAL_AVAILABILITY_CERT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Certificate of Sufficient Coal Availability & Geological Report (Format 2A)','Certificate indicating sufficient coal available in area proposed with relevant exploration report (Format No. 2A)','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORMAT_2A", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,190,'पर्याप्त कोयला उपलब्धता का प्रमाण पत्र और भूवैज्ञानिक रिपोर्ट (प्रारूप 2A)',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('25fc4ea1-e69f-4e48-b7c0-858aec0b3e60'::uuid,'CBA_FORM_VIII_WEBSITE_PUB_3WKS','LAND_ACQ_PROPOSAL','BOOLEAN_DECLARATION','Form VIII Publication on ECL Website (Min 3 Weeks)','Whether kept published in official website of ECL in Form VIII for at least three weeks','{"form_fields": [{"name": "published_date", "type": "date", "label": "Publication Date", "required": true}, {"name": "website_url", "type": "text", "label": "Website URL", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"acqModeId": [1]}',NULL,'{"target_field": "form_viii_published", "target_entity": "project_proposal", "value_on_verify": true}',1,true,200,'क्या फॉर्म VIII में कम से कम 3 सप्ताह के लिए ईसीएल की वेबसाइट पर प्रकाशित किया गया है',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('5ac651b9-3baa-469a-a24e-6d2f820a44be'::uuid,'CBA_CALCULATION_SHEET_COST_LAND','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','CBA Calculation Sheet Showing Cost of Land Acquisition','Calculation sheet showing cost of land acquisition under CBA Act 1957','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1]}',NULL,NULL,1,true,210,'सीबीए अधिनियम के तहत भूमि अधिग्रहण लागत दर्शाने वाली गणना पत्रक',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('d16837ef-697c-42ac-a1d4-67c26a2c58a9'::uuid,'EMP_UNIT_FORMS_ABC_COMPOSITE','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Duly Signed & Verified Form-A, Form-B, and Form-C','Duly signed and properly filled-up FORM-A, FORM-B, and FORM-C','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,20,'विधिवत हस्ताक्षरित और भरे हुए फॉर्म-ए, फॉर्म-बी और फॉर्म-सी',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('c51edede-8c91-4c58-98e1-fc5097ecca98'::uuid,'CBA_TRIBUNAL_DEPOSIT_APPROVAL','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Administrative Approval for Tribunal Deposit (Disputed / Unclaimed Land)','Administrative approval for deposition of compensation amount to Tribunal for disputed/sub-judice lands or unclaimed plots','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1], "conditions": [{"field": "has_disputed_plots", "value": true, "operator": "=="}]}',NULL,NULL,1,false,220,'विवादित/अदावाकृत भूमि के लिए न्यायाधिकरण (Tribunal) में मुआवजा जमा करने की प्रशासनिक स्वीकृति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed');
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('61e7239b-5529-4bf6-88c5-dcb2c0e7d70c'::uuid,'RFCTLARR_BOARD_APPROVAL_COPY','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Board Approval Copy for RFCTLARR Acquisition','A copy of the Board approval for acquisition under RFCTLARR Act 2013','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [2]}',NULL,'{"target_field": "board_approval_attached", "target_entity": "project_proposal", "value_on_verify": true}',1,true,230,'आरएफसीटीएलएआरआर (RFCTLARR) अधिनियम 2013 के तहत अधिग्रहण के लिए बोर्ड अनुमोदन की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('9d380fa6-343c-462b-bdc5-cca4f013a4c7'::uuid,'RFCTLARR_SIA_STUDY_REPORT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Social Impact Assessment (SIA) Study & Consent Report','Social Impact Assessment (SIA) study report and consent of affected families under RFCTLARR Act 2013','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [2]}',NULL,NULL,1,true,240,'सामाजिक प्रभाव आकलन (SIA) अध्ययन रिपोर्ट और प्रभावित परिवारों की सहमति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('d78ed7af-439a-486b-bdff-e097a47601a5'::uuid,'RFCTLARR_CALCULATION_SOLATIUM','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','RFCTLARR Compensation Calculation Sheet (Solatium 100% & Multiplier)','Calculation sheet showing cost of land acquisition under RFCTLARR Act 2013 including market value multiplier, 100% Solatium, and 12% interest','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [2]}',NULL,NULL,1,true,250,'आरएफसीटीएलएआरआर अधिनियम के तहत 100% सोलेशियम और गुणांक सहित मुआवजा गणना पत्रक',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('20a1f0b7-d7ff-4eae-bf1e-d6d2b356a31f'::uuid,'RFCTLARR_RNR_CL3_PACKAGE_ATTACH','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','R&R Scheme Package Attachment (Checklist CL-3)','If rehabilitation of PAF is involved then attach CHECKLIST NO.: CL-3 and all documents as per said checklist under RFCTLARR Act 2013','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [2], "conditions": [{"field": "has_paf_rehabilitation", "value": true, "operator": "=="}]}',NULL,'{"target_field": "cl3_rnr_package_attached", "target_entity": "project_proposal", "value_on_verify": true}',1,false,260,'पुनर्वास (R&R) शामिल होने पर चेकलिस्ट CL-3 और संबंधित पैकेज दस्तावेज संलग्न करें',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('2c1cb3d7-83cf-4ced-9925-9225dc4b60f0'::uuid,'DP_REGISTRATION_MUTATION_COST','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Calculation Sheet for Acquisition, Registration & Mutation Costs','Calculation sheet showing cost of acquisition of all types of land including cost of registration and mutation','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6]}',NULL,NULL,1,true,270,'पंजीकरण और दाखिल-खारिज लागत सहित प्रत्यक्ष खरीद गणना पत्रक',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('d6a45581-66ee-484b-828c-ee888160877d'::uuid,'DP_GOVT_NOTIFIED_CIRCLE_RATES','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Government Notified Market Price / Circle Rate Chart','Copy of Government notified market price of tenancy lands for registration cost calculation','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6]}',NULL,NULL,1,true,280,'पंजीकरण लागत गणना हेतु सरकार द्वारा अधिसूचित बाजार मूल्य (Circle Rate) की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('fd165e43-8f8f-41df-8e72-aaf1e6d5b238'::uuid,'DP_MINE_SITUATION_MUTATION_FEE','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Mine Location Authentic Document (For Mutation Fee Rate)','Copy of authentic document showing situation of project/mine for ascertaining rate of processing fees for mutation','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6]}',NULL,NULL,1,true,290,'दाखिल-खारिज (Mutation) प्रसंस्करण शुल्क की दर तय करने के लिए खदान की स्थिति का दस्तावेज',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('620bab83-9daa-4fff-8149-d019bf2d0e85'::uuid,'DP_LANDOWNERS_AGREEMENT_MINUTES','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Minutes of Meeting with Landowners Accepting Proposed Rates','Minutes of meeting, if held, with landowners for their acceptance with respect to proposed rate of direct purchase','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6]}',NULL,NULL,1,true,300,'प्रस्तावित दर की स्वीकृति के लिए भूस्वामियों के साथ बैठक का कार्यवृत्त',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('690828a3-219e-42e8-895f-0ee0149b6e98'::uuid,'DP_TRIBAL_LAND_DISTRICT_PERMIT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','District Authority Approval for Tribal Land Purchase','Copy of approval of District Authority for purchase of Tribal Land under statutory provisions','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6], "conditions": [{"field": "has_tribal_land", "value": true, "operator": "=="}]}',NULL,'{"target_field": "tribal_land_approval_attached", "target_entity": "project_proposal", "value_on_verify": true}',1,false,310,'आदिवासी भूमि की खरीद हेतु जिला प्राधिकारी के अनुमोदन की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('b45093a4-be07-4c2f-98ea-2244bd2b20a1'::uuid,'DP_DEBOTTAR_DISTRICT_JUDGE_PERMIT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','District Judge Approval for Purchase of Debottar Land','Copy of approval of District Judge for purchase of Debottar Land (Deity land)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6], "conditions": [{"field": "has_debottar_land", "value": true, "operator": "=="}]}',NULL,'{"target_field": "debottar_land_approval_attached", "target_entity": "project_proposal", "value_on_verify": true}',1,false,320,'देवोत्तर भूमि (देवता की भूमि) की खरीद हेतु जिला न्यायाधीश के अनुमोदन की प्रति',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed');
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('b34f2a23-e665-447a-85c1-8a21eb2c3b44'::uuid,'SPECIFIC_PROPOSAL_PURPOSE','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Specific Proposal Stating Purpose & Justification','Specific proposal stating purpose, justification and detailing with respect to acquisition of land','{"max_size_mb": 25, "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "has_proposal_doc", "target_entity": "project_proposal", "value_on_verify": true}',1,true,10,'भूमि अधिग्रहण के उद्देश्य, औचित्य और विवरण को दर्शाने वाला विशिष्ट प्रस्ताव',true,'2026-08-04 15:17:47.927','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('624bd498-b169-4849-9dbf-39803e171b02'::uuid,'QUANTUM_LAND_WITHIN_PR_LIMIT','LAND_ACQ_PROPOSAL','BOOLEAN_DECLARATION','Quantum of Land within Approved Project Limit','Whether Quantum of land to be acquired is within the limit approved in Project Report/ Scheme/ Conceptual report of the Mine/ Project','{"form_fields": [{"name": "approved_limit_ha", "type": "number", "label": "Approved PR Limit (Ha)", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,'{"target_field": "is_within_pr_limit", "target_entity": "project_proposal", "value_on_verify": true}',1,true,20,'क्या अधिग्रहित की जाने वाली भूमि की मात्रा स्वीकृत परियोजना रिपोर्ट/योजना की सीमा के भीतर है',true,'2026-08-04 15:17:47.927','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('2d4803ab-b254-48b9-abeb-ef49f1628552'::uuid,'RECONCILIATION_CERT_FORM_VII','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Reconciliation Certificate (Form VII)','Copy of reconciliation certificate (Form VII)','{"form_fields": [{"name": "form_vii_ref_no", "type": "text", "required": true}], "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "reconciliation_status", "target_entity": "project_proposal", "value_on_verify": "FORM_VII_ATTACHED"}',1,true,40,'समाधान प्रमाण पत्र (फॉर्म VII) की प्रति',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('3cdc5e49-b453-4341-b9d7-8fd0191ccfdf'::uuid,'RNR_PLANNING_GUIDELINE_COMPLIANCE','REHABILITATION_PACKAGE','BOOLEAN_DECLARATION','Rehabilitation Planning Compliance','Whether Rehabilitation Planning has been done according to approved ''Rehabilitation Planning Guideline''','{"form_fields": [{"name": "guideline_ref", "type": "text", "label": "Approved Guideline Ref No", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"has_paf_rehabilitation": true}',NULL,'{"target_field": "is_guideline_compliant", "target_entity": "rehabilitation_package", "value_on_verify": true}',1,true,10,'क्या पुनर्वास योजना अनुमोदित ''पुनर्वास योजना दिशानिर्देश'' के अनुसार की गई है',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('3c67bc48-bcd1-4659-a366-415513fc82d1'::uuid,'RNR_SOCIO_ECONOMIC_STUDY_REPORT','REHABILITATION_PACKAGE','DOCUMENT_UPLOAD','Socio-Economic Study & Baseline Survey Report','Whether Socio-economic study for collection of baseline data has been conducted and report attached','{"form_fields": [{"name": "agency_name", "type": "text", "label": "Executing Agency Name", "required": true}], "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"has_paf_rehabilitation": true}',NULL,'{"target_field": "socio_economic_status", "target_entity": "rehabilitation_package", "value_on_verify": "COMPLETED"}',1,true,20,'सामाजिक-आर्थिक अध्ययन और आधारभूत डेटा संग्रह रिपोर्ट',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('af1132bd-e457-4bd6-aad2-ee8f593bb066'::uuid,'RNR_PAF_CENSUS_IDENTIFICATION','REHABILITATION_PACKAGE','DATA_FORM','Census Report & Displaced Family PAF Identification','Whether census for identification of PAFs has been carried out within stipulated time along with PAF count','{"form_fields": [{"name": "census_date", "type": "date", "label": "Census Report Date", "required": true}, {"name": "total_paf_count", "type": "number", "label": "Total PAF Count", "required": true}, {"name": "resettled_paf_count", "type": "number", "label": "PAF Count for Resettlement Site", "required": true}, {"name": "lumpsum_paf_count", "type": "number", "label": "PAF Count for One-time Lumpsum", "required": true}], "control_type": "DATA_FORM"}','{"has_paf_rehabilitation": true}',NULL,'{"sync_fields": {"total_paf_count": "user_input.total_paf_count"}, "target_field": "total_paf_identified", "target_entity": "rehabilitation_package"}',1,true,30,'पीएएफ (PAF) पहचान हेतु जनगणना रिपोर्ट और परिवारों की संख्या',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('75083536-ea07-4fa1-af40-396da53eeb4a'::uuid,'RNR_COMMITTEE_CONSTITUTION_ORDER','REHABILITATION_PACKAGE','DOCUMENT_UPLOAD','Resettlement & Rehabilitation Committee Constitution Order','Whether ''Resettlement & Rehabilitation Committee'' has been constituted','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"has_paf_rehabilitation": true}',NULL,'{"target_field": "rnr_committee_formed", "target_entity": "rehabilitation_package", "value_on_verify": true}',1,true,40,'पुनर्वास एवं पुनर्व्यवस्थापन समिति गठन का आदेश',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('8ef46ea3-d11c-4ff4-bf98-c4ab64a686c4'::uuid,'RNR_SITE_LAND_REQUIREMENT_DETAILS','REHABILITATION_PACKAGE','DATA_FORM','Rehabilitation Site Location & Plot Allotment Specifications','If PAFs are to be resettled at a rehabilitation site: location, total land area required, and plot area to be allotted per PAF','{"form_fields": [{"name": "site_location", "type": "text", "label": "Site Location / Village", "required": true}, {"name": "total_site_area_ha", "type": "number", "label": "Total Site Area (Ha)", "required": true}, {"name": "plot_size_sqm", "type": "number", "label": "Plot Size per PAF (Sq.m)", "required": true}], "control_type": "DATA_FORM"}','{"has_paf_rehabilitation": true}',NULL,NULL,1,true,50,'पुनर्वास स्थल का स्थान, कुल आवश्यक भूमि और प्रत्येक परिवार को आवंटित भूखंड का क्षेत्रफल',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('e6603482-9640-4c22-8944-8c2609a129cf'::uuid,'RNR_ASSET_VALUATION_SOR_CHARTS','REHABILITATION_PACKAGE','DOCUMENT_UPLOAD','Valuation of Houses, Structures & Approved SOR Charts','Documents showing number of Houses, other Structures and assets in villages with detailed valuation done as per State L.A. Act SOR/Rate charts','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"has_paf_rehabilitation": true}',NULL,NULL,1,true,60,'मकानों, संरचनाओं के मूल्यांकन और स्वीकृत एसओआर (SOR) दर तालिकाओं के दस्तावेज',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL),
	 ('c3ec5bda-4cf8-4bae-a3c2-90b1f2c034e8'::uuid,'RNR_PAF_DISPLACED_CONSENT_MINUTES','REHABILITATION_PACKAGE','DOCUMENT_UPLOAD','Consent of Displaced Families (Meeting Minutes & Agreements)','Consent of ''displaced families'' for proposed rehabilitation (Attach minutes of meeting/ agreement etc.)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"has_paf_rehabilitation": true}',NULL,'{"target_field": "paf_consent_obtained", "target_entity": "rehabilitation_package", "value_on_verify": true}',1,true,70,'प्रस्तावित पुनर्वास के लिए विस्थापित परिवारों की सहमति (बैठक के कार्यवृत्त)',true,'2026-08-05 17:07:25.484','2026-08-05 17:07:25.484',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('a9f5ff6a-2739-4231-bd01-0fbc662cca5d'::uuid,'EMP_UNIT_NOMINEE_APP_FORM_V','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Nominee Application with Form V Details','Application by nominee addressing Head of Colliery/Project Authority attaching details in Form V','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_V", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,'{"target_field": "form_v_status", "target_entity": "employment_proposal", "value_on_verify": "ATTACHED"}',1,true,10,'फॉर्म V विवरण के साथ मनोनीत उम्मीदवार का आवेदन',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('aa73ca77-e702-40c4-8a0d-10f11f5b084a'::uuid,'EMP_UNIT_SELF_DECLARATION_FORM_VI','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Self-Declaration Certificate in Form-VI','Self-declaration Certificate (FORM-VI) duly signed by nominee','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_VI", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,30,'फॉर्म-VI में स्व-घोषणा प्रमाण पत्र',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('5b0248f9-5ec0-4735-b914-4322b8739c6e'::uuid,'EMP_UNIT_STANDARD_ATTESTATION_FORM','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Standard Attestation Form of Candidate','Standard Attestation Form completed and signed by nominee','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,40,'उम्मीदवार का मानक सत्यापन फॉर्म (Attestation Form)',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('e98f36e1-de3f-4ba6-b4ff-f2ebbbb84df5'::uuid,'DP_CNT_JHARKHAND_DRAFT_AGREEMENT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Jharkhand CNT Act Draft Agreement, Affidavit & Indemnity Bond','Additional documents where CNT Act is applicable: Draft Agreement, Draft Affidavit, and Draft Indemnity Bond between ECL and Landowner','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [6], "conditions": [{"field": "is_cnt_applicable", "value": true, "operator": "=="}]}',NULL,NULL,1,false,330,'झारखंड सीएनटी (CNT) अधिनियम हेतु ड्राफ्ट समझौता, शपथ पत्र और क्षतिपूर्ति बंधपत्र',true,'2026-08-06 12:32:44.187','2026-08-06 12:32:44.187','seed','seed'),
	 ('cc9c2215-e898-44c9-90b4-e21bc73d8df6'::uuid,'EMP_UNIT_NOMINATOR_AFFIDAVIT','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Nominator Landowner Affidavit (First Class Magistrate)','Declaration in the form of an Affidavit (solemnized before First Class Magistrate) submitted by landowner/nominator as per SOP Step 2.I','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,50,'प्रथम श्रेणी मजिस्ट्रेट के समक्ष भूस्वामी/नामांकनकर्ता द्वारा शपथ पत्र (Affidavit)',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('20483d0a-5fc3-4eb4-bd2c-c9ad27bf3b31'::uuid,'EMP_UNIT_INDEMNITY_BOND_EXECUTIVE_MAGISTRATE','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Indemnity Bond with Sureties (First Class Executive Magistrate)','An Indemnity Bond solemnized before First Class Executive Magistrate given by nominee with sureties as per SOP Step 4.G','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,60,'प्रथम श्रेणी के कार्यकारी मजिस्ट्रेट द्वारा निष्पादित क्षतिपूर्ति बंधपत्र (Indemnity Bond)',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('56565046-b0a9-49fd-9d42-f1a1fd9142cb'::uuid,'EMP_UNIT_FORM_IV_LAND_POSSESSION_DOC','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Form-IV Land Possession Certificate & Form-VII Reconciliation','A copy of Form-IV (Land possession document) and Reconciliation Certificate in Form-VII','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_IV", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,'{"target_field": "possession_verified", "target_entity": "employment_proposal", "value_on_verify": true}',1,true,70,'फॉर्म-IV (भूमि कब्जा दस्तावेज) और फॉर्म-VII समाधान प्रमाण पत्र',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('d234c7de-224d-4d94-ab8f-e63ab62cada8'::uuid,'EMP_UNIT_LAND_UTILIZATION_FORM_VIII','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Land Utilization Certificate in Form-VIII','Land Utilization Certificate issued by Unit Authority in prescribed format (Form - VIII)','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_VIII", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,80,'इकाई प्राधिकरण द्वारा जारी फॉर्म-VIII में भूमि उपयोगिता प्रमाण पत्र',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('38d5b600-3204-4603-b56e-d9377de2ec9f'::uuid,'EMP_UNIT_LAND_COMPOSITE_SUMMARY_FORM_XI_XII','EMPLOYMENT_PROPOSAL_UNIT','DOCUMENT_UPLOAD','Land Summary in Form-XI & Form-XII Gist','Summary of land offered for employment (in standard Form-XI) and Gist of land offered in Form-XII','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XI", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,90,'फॉर्म-XI (भूमि सारांश) और फॉर्म-XII में पेश की गई भूमि का विवरण',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('44564bd7-58f3-44fb-82d2-aca4ac346e03'::uuid,'EMP_AREA_ROR_EXAMINATION_VETTING','EMPLOYMENT_PROPOSAL_AREA','BOOLEAN_DECLARATION','Verification of RoRs against Computerized Inventory','Whether R.O.Rs of offered plot(s) have been thoroughly examined and verified by Area Land Dealing Officials against computerized land inventory','{"form_fields": [{"name": "verified_by_officer", "type": "text", "label": "Area Officer Name & Designation", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"is_employment_proposal": true}','{"auto_populate": true, "source_chk_cd": "EMP_UNIT_LAND_COMPOSITE_SUMMARY_FORM_XI_XII"}',NULL,1,true,10,'क्या क्षेत्रीय भूमि अधिकारियों द्वारा आरओआर (RoR) और कंप्यूटरीकृत रिकॉर्ड की गहन जांच की गई है',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('92b71605-6b6a-4512-9b38-e499645f0f8f'::uuid,'EMP_AREA_CERTIFICATE_FORM_XXI','EMPLOYMENT_PROPOSAL_AREA','DOCUMENT_UPLOAD','Area Land Dealing Officer Certificate in Form-XXI','Attach certificate in Form-XXI signed by the Area Land Dealing Officer','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XXI", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,'{"target_field": "area_aldo_certified", "target_entity": "employment_proposal", "value_on_verify": true}',1,true,20,'क्षेत्रीय भूमि निपटान अधिकारी द्वारा हस्ताक्षरित फॉर्म-XXI में प्रमाण पत्र',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('b5da2bf3-5747-4217-98dc-9b14b40cf660'::uuid,'EMP_AREA_CELL_COMMITTEE_FORM_XXII','EMPLOYMENT_PROPOSAL_AREA','DOCUMENT_UPLOAD','Area Land Cell Committee Recommendation in Form-XXII','FORM-XXII signed by the Area Land Cell Committee members','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XXII", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,'{"target_field": "alcc_recommendation_status", "target_entity": "employment_proposal", "value_on_verify": "RECOMMENDED"}',1,true,30,'क्षेत्रीय भूमि सेल समिति के सदस्यों द्वारा हस्ताक्षरित फॉर्म-XXII',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('015d8643-48a2-4561-9414-dae3d0dbab9d'::uuid,'EMP_AREA_POLICE_RELATIONSHIP_VERIFICATION','EMPLOYMENT_PROPOSAL_AREA','DOCUMENT_UPLOAD','Police / Relationship Verification Certificate (Form XV / XVA)','Police verification report or on-the-spot relationship verification certificate in Form-XV and Form-XVA regarding landowner and nominee','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XV", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,NULL,1,true,40,'पुलिस सत्यापन रिपोर्ट / फॉर्म-XV में संबंध सत्यापन प्रमाण पत्र',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('02ce0af4-f3a2-4ea4-9c1c-4cffab13b639'::uuid,'EMP_AREA_AGM_RECOMMENDATION_APPROVAL','EMPLOYMENT_PROPOSAL_AREA','DOCUMENT_UPLOAD','Recommendation of Area General Manager (AGM)','Whether employment proposal has been examined and recommended by Area General Manager','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}',NULL,'{"target_field": "agm_approval_status", "target_entity": "employment_proposal", "value_on_verify": "RECOMMENDED_TO_HQ"}',1,true,50,'क्षेत्रीय महाप्रबंधक (AGM) की संस्तुति एवं सिफारिश',true,'2026-08-05 17:08:08.434','2026-08-05 17:08:08.434',NULL,NULL),
	 ('c61a9f3c-d16f-4f37-bb1a-ba478fc9a9c0'::uuid,'EMP_HQ_GIST_EMPLOYMENT_FORM_XIV','EMPLOYMENT_PROPOSAL_HQ','DOCUMENT_UPLOAD','Gist of Employment Proposal in Form-XIV','Gist of Employment proposal prepared in prescribed Form XIV','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XIV", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"is_employment_proposal": true}','{"auto_populate": true, "source_chk_cd": "EMP_AREA_CELL_COMMITTEE_FORM_XXII"}',NULL,1,true,10,'निर्धारित फॉर्म XIV में रोजगार प्रस्ताव का संक्षिप्त विवरण (Gist)',true,'2026-08-05 17:08:39.7','2026-08-05 17:08:39.7',NULL,NULL),
	 ('8e6b79f7-175b-4fb5-994d-18d06db23a64'::uuid,'EMP_HQ_ECL_POSSESSION_MUTATION_CHECK','EMPLOYMENT_PROPOSAL_HQ','BOOLEAN_DECLARATION','Verification of ECL Possession & Mutation Status','Whether land offered is in physical possession of ECL and mutated in favour of ECL (or covered under CBA Act / CNT Act exemption)','{"form_fields": [{"name": "possession_confirmed", "type": "boolean", "required": true}, {"name": "mutation_confirmed", "type": "boolean", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"is_employment_proposal": true}','{"auto_populate": true, "source_chk_cd": "EMP_UNIT_FORM_IV_LAND_POSSESSION_DOC"}',NULL,1,true,20,'क्या भूमि ईसीएल के भौतिक कब्जे में है और ईसीएल के पक्ष में दाखिल-खारिज (Mutation) है',true,'2026-08-05 17:08:39.7','2026-08-05 17:08:39.7',NULL,NULL),
	 ('2bec312a-cbdc-46a6-8923-ea3e350b655f'::uuid,'EMP_HQ_CIL_RNR_POLICY_COMPLIANCE_CHECK','EMPLOYMENT_PROPOSAL_HQ','BOOLEAN_DECLARATION','CIL R&R Policy Compliance & Deviation Approvals','Whether proposal is in line with R&R Policy of CIL and any relaxation reference obtained from Competent Authority is attached','{"form_fields": [{"name": "is_rnr_policy_compliant", "type": "boolean", "required": true}, {"name": "relaxation_ref_no", "type": "text", "required": false}], "control_type": "BOOLEAN_DECLARATION"}','{"is_employment_proposal": true}',NULL,'{"target_field": "hq_approval_status", "target_entity": "employment_proposal", "value_on_verify": "APPROVED_BY_CMD"}',1,true,30,'क्या प्रस्ताव कोल इंडिया की आरएंडआर (R&R) नीति के अनुरूप है और सक्षम प्राधिकारी का अनुमोदन संलग्न है',true,'2026-08-05 17:08:39.7','2026-08-05 17:08:39.7',NULL,NULL),
	 ('cd11297b-d9a0-44b1-851f-78199a871c3f'::uuid,'REVENUE_PLAN_MOUZA_COLOR_WASH','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Revenue Plan with Boundary & Land Type Color Washing','A revenue plan showing boundary of the approved/ authorized project/ working area, important surface features, land owned by ECL, Government land, Patta Land, Forest land and area of land to be acquired for the workings as well as other ancillary activities approved for the project/ mine washed in different colors.','{"max_size_mb": 50, "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "has_revenue_plan", "target_entity": "project_proposal", "value_on_verify": true}',1,true,50,'विभिन्न रंगों में दर्शाया गया सीमा और भूमि प्रकार वाला राजस्व मानचित्र',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('e5c0f10a-0661-4784-a49d-9734d2342e81'::uuid,'FOREST_CLEARANCE_DOC','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Forest Clearance (Stage-I / Stage-II)','Copy of Forest Clearance, if obtained','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.forest_ha", "value": 0, "operator": ">"}]}',NULL,'{"target_field": "forest_clearance_status", "target_entity": "project_proposal", "value_on_verify": "ATTACHED"}',1,false,80,'वन मंजूरी की प्रति (यदि प्राप्त हो)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('017d89ac-acfd-4237-a6e9-2c4c9c7c212d'::uuid,'CERT_FIVE_POINT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','FIVE-POINT Certificate in Form XVI','A FIVE-POINT certificate in Form XVI','{"control_type": "DOCUMENT_UPLOAD", "template_code": "FORM_XVI", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,90,'फॉर्म XVI में पांच-बिंदु (FIVE-POINT) प्रमाण पत्र',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('20c13e96-5c97-4051-808c-45011439f4d5'::uuid,'STANDARD_CHECKLIST_ECL_ORDER','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Standard Checklist (ECL Office Orders 2005)','A standard ''Check List'' as circulated through Office Order (Ref. No. ECL/CMD/LRE/ANG/Check-list/1071 Date 25th Nov 2005 & Date 22 March 2005)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,100,'कार्यालय आदेश (ईसीएल/सीएमडी/एलआरई 2005) के माध्यम से परिचालित मानक चेक लिस्ट',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('010093e8-c53b-4f57-8ea7-7505b79a1c6b'::uuid,'TECHNO_ECONOMIC_REPORT_ACQ','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Techno-Economic Report for Land Acquisition','Techno-Economic Report'' showing estimated total financial involvement and capital involvement for cost land acquisition, rehabilitation and employment for land','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,120,'भूमि अधिग्रहण, पुनर्वास और रोजगार की लागत दर्शाने वाली तकनीकी-आर्थिक रिपोर्ट',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('8c73e869-2edb-453d-b05b-a359b54fcf7e'::uuid,'CALCULATION_SHEET_COST_LAND','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Calculation Sheet Showing Cost of Land Acquisition','Calculation sheet showing cost of land acquisition','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,130,'भूमि अधिग्रहण की लागत दर्शाने वाली गणना पत्रक',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('67e20fc9-e0c5-4530-b37e-a16ab15717f0'::uuid,'DOCS_RATES_TENANCY_LAND','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Documents — Tenancy Land Rates','Documents to substantiate the rates of compensation of Tenancy land like copy of agreement with landowners/ previous settlement of compensation, minutes of meeting with landowners, Government certified market value etc. for current land or for chronologically nearest previous case of possession of land','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.tenancy_ha", "value": 0, "operator": ">"}]}',NULL,NULL,1,true,140,'किरायेदारी भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('506913d7-2312-4d20-a4ae-120c4131c498'::uuid,'DOCS_RATES_GOVT_PATTA_LAND','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Documents — Government / Patta Land Rates','Documents to substantiate the rates of compensation of Government land/ Patta Land like copy of Government certified market value/ demand of District Authority etc.','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.govt_ha", "value": 0, "operator": ">"}]}',NULL,NULL,1,true,150,'सरकारी/पट्टा भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('ce567c58-fcf6-4f48-82b5-ec376702a119'::uuid,'POSS_JUSTIFICATION_HEAD_OF_MINE','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Justification & Recommendation by Head of Mine / Project','Justification and recommendation by Head of the Mine/ Project','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,300,'खदान/परियोजना प्रमुख द्वारा औचित्य और सिफारिश',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('e1d9b951-4fee-4777-a36d-78983d0c3352'::uuid,'DOCS_RATES_FOREST_LAND','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Documents — Forest Land Rates','Documents to substantiate the rates of compensation of Forest land like copy of demand of State Forest department etc.','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "ACQUISITION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.forest_ha", "value": 0, "operator": ">"}]}',NULL,NULL,1,true,160,'वन भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('0abfd39f-4a58-475f-9446-d07bfba5cc38'::uuid,'POSS_RELEVANT_PAGES_PR','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Relevant Pages of Approved PR / Scheme (Possession)','Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project (For Possession)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "RELEVANT_PAGES_APPROVED_PR"}',NULL,1,true,180,'कब्जे हेतु स्वीकृत पीआर/योजना के प्रासंगिक पृष्ठों की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('f214f328-19be-4fd0-8b57-a83c95c58589'::uuid,'POSS_SANCTION_GAZETTE_SEC_9_11','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Gazette Sanction Orders (Section 9 & 11 CBA Act)','Copies of Sanction Orders published in Gazette of India under section 9 and 11 of CBA (A&D) Act 1957','{"form_fields": [{"name": "sec_9_gazette_ref", "type": "text"}, {"name": "sec_11_gazette_ref", "type": "text"}], "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "cba_notification_status", "target_entity": "project_proposal", "value_on_verify": "SEC_11_NOTIFIED"}',1,true,190,'सीबीए अधिनियम की धारा 9 और 11 के तहत भारत के राजपत्र में प्रकाशित स्वीकृति आदेशों की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('1c20d21f-5318-4392-a626-987af38e9c29'::uuid,'POSS_SCHEDULE_LAND_PLOT_DETAILS','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Schedule of Land for Possession (Plot-wise)','Two copies of Schedule of land furnishing details like mouza name, plot no, land type, total area, area already possessed, area for which possession is to be taken, remarks if any','{"columns": ["mouza_name", "plot_no", "land_type", "total_area", "already_possessed_area", "proposed_possession_area"], "control_type": "TABULAR_ABSTRACT", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "possession_proposal_status", "target_entity": "land_schedule", "value_on_verify": "SUBMITTED"}',1,true,200,'कब्जे हेतु प्रस्तावित भूमि की भूखंड-वार अनुसूची (2 प्रतियां)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('57d0cb82-7e94-4193-a53b-bcda66fc8c4c'::uuid,'POSS_MOUZA_LAND_TYPE_ABSTRACT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Mouza-wise & Land Type-wise Possession Abstract','Mouza wise and land type wise abstract of land which has been proposed for possession','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "SCHEDULE_LAND_TABULAR_MOUZA"}',NULL,1,true,210,'कब्जे के लिए प्रस्तावित भूमि का मौजा-वार और भूमि प्रकार-वार सारांश',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('783aeb7a-034a-45fc-a476-e2addb46a7ee'::uuid,'POSS_RECONCILIATION_CERT_FORM_VII','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Reconciliation Certificate (Form VII - Possession)','Copy of Reconciliation Certificate (Form VII) for possession','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "RECONCILIATION_CERT_FORM_VII"}',NULL,1,true,220,'कब्जे हेतु समाधान प्रमाण पत्र (फॉर्म VII) की प्रति',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('204a34c8-b91f-4930-9478-c35fcb93396c'::uuid,'POSS_REVENUE_PLAN_LAND_UTILIZATION','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Revenue Plan & Year-wise Land Utilization Plan','A Revenue plan (mouza plan) showing concerned land area which is to be possessed and also showing project boundary and year-wise land utilization plan','{"max_size_mb": 50, "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,230,'कब्जे हेतु मौजा मानचित्र एवं वर्षवार भूमि उपयोग योजना',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('00e4ec4b-c97b-49a6-b03f-2803fe098410'::uuid,'POSS_INVOLVEMENT_EMPLOYMENT_COUNT','LAND_ACQ_PROPOSAL','DATA_FORM','Employment Involvement Details for Possession','Number of employments involved, if any for proposed possession','{"form_fields": [{"name": "possession_employment_count", "type": "number", "label": "Employments for Possession", "required": true}], "control_type": "DATA_FORM"}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "INVOLVEMENT_EMPLOYMENT_COUNT"}',NULL,1,true,240,'प्रस्तावित कब्जे से संबंधित रोजगार की संख्या',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('30dbf4af-ac6d-4630-9e81-4442703fb787'::uuid,'POSS_TECHNO_ECONOMIC_REPORT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Techno-Economic Report for Land Possession','Techno-Economic Report showing total financial involvement for proposed possession of Tenancy land, Govt. land and Forest land','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,250,'प्रस्तावित कब्जे के लिए कुल वित्तीय भागीदारी दर्शाने वाली तकनीकी-आर्थिक रिपोर्ट',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('4674f4a8-3484-4f63-bd83-563090a7db9d'::uuid,'POSS_CALCULATION_COMPENSATION_RATES','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Calculation Sheet — Rates of Compensation by Category','Calculation showing details of rates of compensation for each category of land','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,260,'भूमि की प्रत्येक श्रेणी के लिए मुआवजे की दरों का विवरण दर्शाने वाली गणना',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('3c321ab2-df81-4642-bf3f-222e989ec9fa'::uuid,'POSS_DOCS_RATES_TENANCY','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Compensation Documents — Tenancy Land (Possession)','Documents to substantiate the rates of compensation of Tenancy land like copy of agreement with landowners/ previous settlement of compensation, minutes of meeting with landowners, Government certified market value etc.','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.tenancy_ha", "value": 0, "operator": ">"}]}','{"auto_populate": true, "source_chk_cd": "DOCS_RATES_TENANCY_LAND"}',NULL,1,true,270,'किरायेदारी भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज (कब्जे हेतु)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('35e31dc1-68df-43c4-a44c-398165a63e71'::uuid,'POSS_DOCS_RATES_GOVT_PATTA','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Compensation Documents — Govt / Patta Land (Possession)','Documents to substantiate the rates of compensation of Government land/ Patta Land like copy of Government certified market value/ demand of District Authority etc.','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.govt_ha", "value": 0, "operator": ">"}]}','{"auto_populate": true, "source_chk_cd": "DOCS_RATES_GOVT_PATTA_LAND"}',NULL,1,true,280,'सरकारी/पट्टा भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज (कब्जे हेतु)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('6b545756-8866-499e-8d84-7b9b321f9821'::uuid,'POSS_DOCS_RATES_FOREST','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Substantiating Compensation Documents — Forest Land (Possession)','Documents to substantiate the rates of compensation of Forest land like copy of demand of State Forest department etc.','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1], "conditions": [{"field": "land_breakdown.forest_ha", "value": 0, "operator": ">"}]}','{"auto_populate": true, "source_chk_cd": "DOCS_RATES_FOREST_LAND"}',NULL,1,true,290,'वन भूमि के मुआवजे की दर को प्रमाणित करने वाले दस्तावेज (कब्जे हेतु)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('163ea8b6-fc70-4be2-b791-b77960c395d4'::uuid,'POSS_REPORT_ALCC_EXAMINATION','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Area Land Cell Committee Report on Possession Proposal','Report on examination of the proposal by the ''Area Land Cell Committee'' and recommendation thereof','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,310,'क्षेत्रीय भूमि सेल समिति द्वारा कब्जे के प्रस्ताव की जांच रिपोर्ट और सिफारिश',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('89edcb41-6c21-4669-95a7-b74f938f4864'::uuid,'POSS_RECOMMENDATION_AGM','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Recommendation of Area General Manager for Possession','Recommendation of the Area General Manager for taking possession','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "possession_agm_approval", "target_entity": "project_proposal", "value_on_verify": "APPROVED"}',1,true,320,'कब्जा लेने के लिए क्षेत्रीय महाप्रबंधक (AGM) की संस्तुति',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('5d6eb3c0-ddcd-403b-a1f5-b3889a6b386b'::uuid,'RELEVANT_PAGES_APPROVED_PR','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Relevant Pages of Approved PR / Scheme','Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"acqModeId": [1, 2, 3, 4, 5, 6, 8]}',NULL,NULL,1,true,60,'स्वीकृत पीआर/योजना/वैचारिक रिपोर्ट के प्रासंगिक पृष्ठों की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-06 12:32:44.187',NULL,'seed'),
	 ('beb672d6-8146-4791-9ea0-9032a892b0f0'::uuid,'POSS_FORM_VIII_ECL_WEBSITE_PUB','LAND_ACQ_PROPOSAL','BOOLEAN_DECLARATION','Form VIII Publication on ECL Website (Min 3 Weeks)','Whether kept published in official website of ECL in Form VIII for at least three weeks','{"form_fields": [{"name": "published_date", "type": "date", "label": "Publication Date on Website", "required": true}, {"name": "website_url", "type": "text", "label": "ECL Portal Link", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "form_viii_published", "target_entity": "project_proposal", "value_on_verify": true}',1,true,330,'क्या फॉर्म VIII में कम से कम तीन सप्ताह के लिए ईसीएल की आधिकारिक वेबसाइट पर प्रकाशित किया गया है',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('a84f1049-9c1d-478a-8918-b57a739df03d'::uuid,'POSS_COMPLAINTS_RESOLVED_BY_AGM','LAND_ACQ_PROPOSAL','BOOLEAN_DECLARATION','Complaints Resolution & Schedule Modification by AGM','Whether complaints have been resolved by Area General Manager and schedule of land for possession has been modified accordingly','{"form_fields": [{"name": "complaints_received_count", "type": "number", "label": "Complaints Received", "required": true}, {"name": "complaints_resolved_count", "type": "number", "label": "Complaints Resolved", "required": true}], "control_type": "BOOLEAN_DECLARATION"}','{"step": "POSSESSION_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "possession_complaints_resolved", "target_entity": "project_proposal", "value_on_verify": true}',1,true,340,'क्या क्षेत्रीय महाप्रबंधक द्वारा शिकायतों का समाधान किया गया है और भूमि अनुसूची में संशोधन किया गया है',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('cffe9518-40be-4571-bbba-c90df5155c2e'::uuid,'PAYROLL_COPIES_APPROVED_PR','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Copies of Approved PR / Scheme (Payroll Approval)','Copies of approved PR/ Scheme of the Mine/ Project','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "RELEVANT_PAGES_APPROVED_PR"}',NULL,1,true,350,'पेरोल अनुमोदन हेतु खदान/परियोजना की स्वीकृत पीआर/योजना की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('cf544d77-a47e-4f34-8015-49a412940b98'::uuid,'PAYROLL_COMPETENT_AUTH_POSS_APPROVAL','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Competent Authority Approval for Possession of Specific Plots','Approval of competent Authority for taking possession of specific plots','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "POSS_RECOMMENDATION_AGM"}',NULL,1,true,360,'विशिष्ट भूखंडों का कब्जा लेने के लिए सक्षम प्राधिकारी की स्वीकृति',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('b9e7696a-887d-440b-a8b3-70ab1939d5f3'::uuid,'PAYROLL_GAZETTE_SEC_9_11_ORDERS','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Gazette Sanction Orders under Section 9 & 11 CBA Act','Copies of Sanction Orders published in Gazette of India under section 9 and 11 of CBA (A&D) Act 1957','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "POSS_SANCTION_GAZETTE_SEC_9_11"}',NULL,1,true,370,'धारा 9 और 11 सीबीए अधिनियम के तहत भारत के राजपत्र में प्रकाशित स्वीकृति आदेशों की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('f047ee1c-63fc-48d7-bc18-51bc50c097ad'::uuid,'PAYROLL_MARKET_VALUE_CALC_ANNEXURE','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Annexure of Market Value & Sample Compensation Calculation','An Annexure showing calculations related to determination of market value of lands, sample calculation for determination of compensation','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,380,'भूमि के बाजार मूल्य निर्धारण और मुआवजे की गणना दर्शाने वाला अनुलग्नक',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('b37d88b0-11a2-49ba-82e4-9cef503687a2'::uuid,'PAYROLL_STATUTE_PROVISIONS_DETAILS','LAND_ACQ_PROPOSAL','DATA_FORM','Statutory Provisions Details (RFCTLARR / CBA 1957)','Details of the schedules and provisions of RFCTLARR Act, 2013 or any other prevalent statute under which the Compensation Payroll has been prepared','{"form_fields": [{"name": "governing_statute", "type": "select", "options": ["CBA_SEC_14", "RFCTLARR_2013", "OTHER"], "required": true}], "control_type": "DATA_FORM"}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,390,'जिस कानून (RFCTLARR / CBA) के तहत मुआवजा पेरोल तैयार किया गया है उसका विवरण',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('ac95eac2-2763-4c48-87a6-7e5764fc595c'::uuid,'PAYROLL_MINUTES_VILLAGERS_AGREEMENT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Minutes of Meetings / Agreement with Villagers (Sec 14(1) CBA)','Minutes of meetings/ Agreement with villagers (Particularly important if the Compensation Payroll has been prepared under section 14(1) of CBA (A&D) Act 1957)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}',NULL,NULL,1,true,400,'ग्रामीणों के साथ बैठक के कार्यवृत्त/समझौता (विशेष रूप से धारा 14(1) सीबीए अधिनियम के तहत)',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL);
INSERT INTO master.chklist_requirement_rule (chk_id,chk_cd,module_code,requirement_type,title,description,input_schema,show_if,inherit_from,sync_to_parent,min_responses_required,is_mandatory,display_order,local_vernacular,is_active,entry_ts,updt_ts,entry_by,updt_by) VALUES
	 ('8e68d80b-6b6e-4fdb-af04-a3d196700878'::uuid,'PAYROLL_JOINT_NO_PRIOR_PAYMENT_CERT','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Joint Certificate of No Prior Payment, R&R, or Employment','A certificate signed by Surveyor, Land dealing official, Manager, Agent/Project officer, Area Land Dealing Officer, members of Area land Cell stating that no compensation has been paid, no R&R benefit and no employment has been provided against the land involved in the proposed compensation payroll earlier.','{"form_fields": [{"name": "signatory_surveyor", "type": "text"}, {"name": "signatory_po", "type": "text"}], "control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "no_prior_benefit_certified", "target_entity": "compensation_payroll", "value_on_verify": true}',1,true,410,'सर्वेक्षक, भूमि अधिकारी, प्रबंधक, एजेंट/पीओ, एएलडीओ, एरिया लैंड सेल द्वारा हस्ताक्षरित प्रमाण पत्र कि पहले कोई मुआवजा, आरएंडआर या रोजगार नहीं दिया गया है',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('695c17a7-4e56-4e68-8152-3295c5098c96'::uuid,'PAYROLL_RECONCILIATION_FORM_VII','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Reconciliation Certificate Copies (Form VII - Payroll)','Copies of reconciliation certificates (FORM-VII)','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}','{"auto_populate": true, "source_chk_cd": "RECONCILIATION_CERT_FORM_VII"}',NULL,1,true,420,'समाधान प्रमाण पत्र (फॉर्म-VII) की प्रतियां',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL),
	 ('916e6504-ed27-4e2b-a07f-609d02023560'::uuid,'PAYROLL_ALCC_AGM_RECOMMENDATION','LAND_ACQ_PROPOSAL','DOCUMENT_UPLOAD','Area Land Cell & AGM Recommendation for Compensation Payroll','Recommendation of Area Land Cell and Area General Manager','{"control_type": "DOCUMENT_UPLOAD", "requires_page_no": true, "allowed_file_types": ["pdf"]}','{"step": "COMPENSATION_PAYROLL_APPROVAL", "acqModeId": [1]}',NULL,'{"target_field": "payroll_approval_status", "target_entity": "compensation_payroll", "value_on_verify": "APPROVED_BY_AGM"}',1,true,430,'मुआवजा पेरोल हेतु क्षेत्रीय भूमि सेल और क्षेत्रीय महाप्रबंधक (AGM) की संस्तुति',true,'2026-08-04 15:31:45.323','2026-08-04 15:31:45.323',NULL,NULL);
