import type { PrismaClient } from '@prisma/client'

export async function seedChkMasterNew(db: PrismaClient) {
  console.log('🌱 Seeding chk_master_new...')

  const checks = [
    { chk_id: 26, chk_description: "Recommendation of the Area General Manager", chk_type: "acquisition" },
    { chk_id: 42, chk_description: "Whether kept published on the official website of ECL in Form VIII for at least three weeks (Give Notification Date)", chk_type: "possession" },
    { chk_id: 41, chk_description: "Recommendation of the Area General Manager", chk_type: "possession" },
    { chk_id: 64, chk_description: "Recommendation of the Area General Manager", chk_type: "acquisition" },
    { chk_id: 83, chk_description: "Recommendation of the Area General Manager", chk_type: "acquisition" },
    { chk_id: 43, chk_description: "Whether complaints, if any, have been resolved by the Area General Manager and the schedule of land for possession has been modified accordingly", chk_type: "possession" },
    { chk_id: 103, chk_description: "Whether valuation of assets has been done as per the standard valuation method of the L. A. Act. of the concerned State Govt.", chk_type: "rr_packg" },
    { chk_id: 39, chk_description: "Justification and recommendation by the Head of the Mine/ Project", chk_type: "possession" },
    { chk_id: 68, chk_description: "Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 50, chk_description: "Copies of statutory clearances like approval obtained from DGMS etc., if obtained", chk_type: "acquisition" },
    { chk_id: 99, chk_description: "If PAFs are to be resettled at a rehabilitation site, then", chk_type: "rr_packg" },
    { chk_id: 85, chk_description: "Whether Rehabilitation Planning has been done according to the approved Rehabilitation Planning Guideline", chk_type: "rr_packg" },
    { chk_id: 87, chk_description: "Whether a Socio-economic study for collection of baseline data has been conducted", chk_type: "rr_packg" },
    { chk_id: 94, chk_description: "Names and locations of villages to be shifted", chk_type: "rr_packg" },
    { chk_id: 95, chk_description: "Date of submission of the report of census", chk_type: "rr_packg" },
    { chk_id: 97, chk_description: "Number of PAFs to be resettled at any rehabilitation site", chk_type: "rr_packg" },
    { chk_id: 100, chk_description: "Status of acquisition of the land required for the rehabilitation site", chk_type: "rr_packg" },
    { chk_id: 101, chk_description: "Status of possession of the land required for the rehabilitation site", chk_type: "rr_packg" },
    { chk_id: 108, chk_description: "Details of deviation from the provision of prevalent R&R policy of CIL and relaxation sought, if any", chk_type: "rr_packg" },
    { chk_id: 90, chk_description: "Whether identity cards have been issued to the displaced families", chk_type: "rr_packg" },
    { chk_id: 91, chk_description: "Whether the Resettlement & Rehabilitation Committee has been constituted", chk_type: "rr_packg" },
    { chk_id: 120, chk_description: "Application requesting MOC for issue of Gazette notification under section 7(1) giving details of coal block.", chk_type: "acquisition" },
    { chk_id: 126, chk_description: "Two file upload section 1) Hindi Format No. 2D  2) English Format No. 2D", chk_type: "acquisition" },
    { chk_id: 128, chk_description: "Certificate confirming that the Plans & Schedules have been prepared on the basis of land records of the State Revenue Authority. (Specimen of the certificate is given at Format No.1C)", chk_type: "acquisition" },
    { chk_id: 130, chk_description: "Certificate confirming that the area proposed to be notified under section 7(1) is the same or within the boundary of the area notified under section 4(1). (Specimen of the certificate is given at Format No.2B)", chk_type: "acquisition" },
    { chk_id: 88, chk_description: "Details of the Agency/Committee framed by GM, which has carried out the socio-economic study", chk_type: "rr_packg" },
    { chk_id: 102, chk_description: "Documents showing the number of Houses, other Structures and assets in the said villages with detailed specifications of the said assets and valuation thereof.", chk_type: "rr_packg" },
    { chk_id: 107, chk_description: "Copies of relevant pages of the approved Project Report/ Scheme/ Conceptual Report along with the order of approval by the competent authority", chk_type: "rr_packg" },
    { chk_id: 111, chk_description: "Consent of displaced families for proposed rehabilitation (Attach minutes of meeting/ agreement etc.)", chk_type: "rr_packg" },
    { chk_id: 132, chk_description: "If Rehabilitation of PAFs are involved then, whether actions for socio-economic study/ census of the project affected families within two months of the notification u/s 7 date have been taken", chk_type: "acquisition" },
    { chk_id: 138, chk_description: "Weather satellite images of the acquired area have been captured?", chk_type: "acquisition" },
    { chk_id: 165, chk_description: "Weather System Improvement Norm’ regarding rehabilitation of PAFS have been followed", chk_type: "asset_rr" },
    { chk_id: 223, chk_description: "Submit all documents required for Notification under section 9 to General Manager (LRE).", chk_type: "acquisition" },
    { chk_id: 147, chk_description: "Compensation Payroll in Standard Form 1A and 1B", chk_type: "compensation" },
    { chk_id: 152, chk_description: "Recommendation of Area Land Cell and Area General Manager", chk_type: "compensation" },
    { chk_id: 157, chk_description: "The Compensation Payroll bill", chk_type: "asset_rr" },
    { chk_id: 15, chk_description: "Copies of statutory clearances like approval obtained from DGMS etc., if obtained", chk_type: "acquisition" },
    { chk_id: 164, chk_description: "Recommendation of Area Land Cell and Area General Manager", chk_type: "asset_rr" },
    { chk_id: 231, chk_description: "Send one original copy and one photocopy of the above newspaper publications to the General Manager (LRE).", chk_type: "acquisition" },
    { chk_id: 227, chk_description: "Submit all documents required for Notification under section 11 to General Manager (LRE).", chk_type: "acquisition" },
    { chk_id: 78, chk_description: "Calculation sheet showing cost of land acquisition", chk_type: "acquisition" },
    { chk_id: 186, chk_description: "Reconciliation Certificate in Form-VII", chk_type: "emp_prop" },
    { chk_id: 221, chk_description: "Paste copies of Notification u/s 11 along with the schedule of land as notified u/s 9 at Panchayet Bhawnas and at other conspicuous places in the mouzas where the acquisition has taken place. ", chk_type: "acquisition" },
    { chk_id: 222, chk_description: "Proclaim the same in nearby areas/villages by the beat of drum. ", chk_type: "acquisition" },
    { chk_id: 207, chk_description: "Whether possession of land has been obtained from the last transferee of the land", chk_type: "emp_prop" },
    { chk_id: 209, chk_description: "Is Patta land involved in the employment?", chk_type: "emp_prop" },
    { chk_id: 215, chk_description: "Is Debottar land involved in the employment?", chk_type: "emp_prop" },
    { chk_id: 218, chk_description: "Is Tribal land involved in the employment?", chk_type: "emp_prop" },
    { chk_id: 180, chk_description: "Whether the above documents have been countersigned by the Area Land dealing officer mentioning his/ her full name, designation, date and seal.", chk_type: "emp_prop" },
    { chk_id: 183, chk_description: "Ownership certificate of concerned Circle officer/BL&LRO in favour of nominator of employment.", chk_type: "emp_prop" },
    { chk_id: 173, chk_description: "Self-declaration Certificate (FORM-VI)", chk_type: "emp_prop" },
    { chk_id: 106, chk_description: "Total capital involvement for R&R of the PAFs along with calculation details", chk_type: "rr_packg" },
    { chk_id: 11, chk_description: "Schedule of land in tabular form with land type-wise and mouza-wise abstract", chk_type: "acquisition" },
    { chk_id: 12, chk_description: "Copy of reconciliation certificate (Form VII)", chk_type: "acquisition" },
    { chk_id: 16, chk_description: "Copy of Forest Clearance, if obtained", chk_type: "acquisition" },
    { chk_id: 17, chk_description: "A FIVE-POINT certificate in Form XVI", chk_type: "acquisition" },
    { chk_id: 18, chk_description: "A standard Check List as circulated through Office Order (Ref. No. ECL/CMD/LRE/ANG/Check-list/1071 Date 25th Nov 2005)", chk_type: "acquisition" },
    { chk_id: 21, chk_description: "Calculation sheet showing the cost of land acquisition", chk_type: "acquisition" },
    { chk_id: 23, chk_description: "Documents to substantiate the rates of compensation of Government land/ Patta Land like copy of Government certified market value/ demand of District Authority etc.", chk_type: "acquisition" },
    { chk_id: 46, chk_description: "Schedule of land in tabular form with land type-wise and mouza-wise abstract", chk_type: "acquisition" },
    { chk_id: 47, chk_description: "Copy of reconciliation certificate (Form VII)", chk_type: "acquisition" },
    { chk_id: 70, chk_description: "Copy of reconciliation certificate (Form VII)", chk_type: "acquisition" },
    { chk_id: 51, chk_description: "Copy of Forest Clearance, if obtained", chk_type: "acquisition" },
    { chk_id: 73, chk_description: "Copy of Forest Clearance, if obtained", chk_type: "acquisition" },
    { chk_id: 52, chk_description: "A FIVE-POINT certificate in Form XVI", chk_type: "acquisition" },
    { chk_id: 74, chk_description: "A FIVE-POINT certificate in Form XVI", chk_type: "acquisition" },
    { chk_id: 53, chk_description: "A standard Check List as circulated through Office Order (Ref. No. ECL/CMD/LRE/ANG/Check-list/1071 Date 25th Nov 2005)", chk_type: "acquisition" },
    { chk_id: 60, chk_description: "Documents to substantiate the rates of compensation of Government land/ Patta Land like a copy of Government certified market value/ demand of District Authority etc.", chk_type: "acquisition" },
    { chk_id: 61, chk_description: "Documents to substantiate the rates of compensation of Forest land like copy of demand of State Forest department etc.", chk_type: "acquisition" },
    { chk_id: 28, chk_description: "Copies of Sanction Orders published in the Gazette of India under sections 9 and 11 of the CBA (A&D) Act 1957", chk_type: "possession" },
    { chk_id: 30, chk_description: "Mouza wise and land type wise abstract of land which has been proposed for possession", chk_type: "possession" },
    { chk_id: 31, chk_description: "Copy of Reconciliation Certificate (Form VII)", chk_type: "possession" },
    { chk_id: 34, chk_description: "Techno-Economic Report showing total financial involvement for proposed possession of Tenancy land, Govt. land and Forest land", chk_type: "possession" },
    { chk_id: 35, chk_description: "Calculation showing details of rates of compensation for each category of land", chk_type: "possession" },
    { chk_id: 38, chk_description: "Documents to substantiate the rates of compensation of Forest land like copies of demands of State Forest department etc.", chk_type: "possession" },
    { chk_id: 170, chk_description: "Duly signed and properly filled-up FORM-A", chk_type: "emp_prop" },
    { chk_id: 171, chk_description: "Duly signed and properly filled-up FORM-B", chk_type: "emp_prop" },
    { chk_id: 172, chk_description: "Duly signed and properly filled-up FORM-C", chk_type: "emp_prop" },
    { chk_id: 58, chk_description: "Copy of Government notified market price of tenancy lands for registration cost calculation.", chk_type: "acquisition" },
    { chk_id: 62, chk_description: "Minutes of meeting, if held, with landowners for their acceptance with respect to the proposed rate", chk_type: "acquisition" },
    { chk_id: 65, chk_description: "Copy of approval of District Authority for purchase of Tribal Land", chk_type: "acquisition" },
    { chk_id: 116, chk_description: "Certificate confirming that the Plans or village Schedules have been prepared on the basis of Survey of India Toposheet/ Revenue plan. (Specimen of the certificate is given at Format No.1C)", chk_type: "acquisition" },
    { chk_id: 81, chk_description: "Documents to substantiate the rates of compensation of Forest land like copies of demands of State Forest department etc.", chk_type: "acquisition" },
    { chk_id: 145, chk_description: "Copies of Sanction Orders published in the Gazette of India under sections 9 and 11 of the CBA (A&D) Act 1957", chk_type: "compensation" },
    { chk_id: 2, chk_description: "Copy of Notification under section 7", chk_type: "acquisition" },
    { chk_id: 3, chk_description: "Copy of Notification under section 9", chk_type: "acquisition" },
    { chk_id: 119, chk_description: "A copy of the Board approval", chk_type: "acquisition" },
    { chk_id: 169, chk_description: "Bio-data of the Nominee as per Activity Step 4.B", chk_type: "emp_prop" },
    { chk_id: 133, chk_description: "Application requesting MOC for issue of Gazette notification under section 9(1) giving details of coal block and copy of section 4(1) and 7(1) notification of the coal block.", chk_type: "acquisition" },
    { chk_id: 139, chk_description: "Application requesting MOC for issue of Gazette notification under section 11(1)", chk_type: "acquisition" },
    { chk_id: 142, chk_description: "A draft order under Section 11(1) of the CBA Act in respect of the coal block / area in English and in Hindi (both hard copy as well as soft copy). (Specimen of the draft notification is given at Format No . 4A)", chk_type: "acquisition" },
    { chk_id: 143, chk_description: "Copies of approved PR/ Scheme of the Mine/ Project", chk_type: "compensation" },
    { chk_id: 144, chk_description: "Approval of competent Authority for taking possession of specific plots", chk_type: "compensation" },
    { chk_id: 154, chk_description: "Approval of competent Authority for taking possession of specific plots", chk_type: "asset_rr" },
    { chk_id: 149, chk_description: "Minutes of meetings/Agreements with villagers (Particularly important if the Compensation Payroll has been prepared under section 14(1) of CBA (A&D) Act 1957)", chk_type: "compensation" },
    { chk_id: 151, chk_description: "Copies of reconciliation certificates (FORM-VII)", chk_type: "compensation" },
    { chk_id: 153, chk_description: "Copies of approved PR/ Scheme of the Mine/ Project showing the provisions for shifting of the village in question", chk_type: "asset_rr" },
    { chk_id: 158, chk_description: "Copy of approval of R&R package with all details and relaxation of provisions of R&R Policy/ Norms obtained.", chk_type: "asset_rr" },
    { chk_id: 159, chk_description: "Copy of the details of the demographic survey done in the village", chk_type: "asset_rr" },
    { chk_id: 161, chk_description: "Details of the measurement and calculations related to the structures", chk_type: "asset_rr" },
    { chk_id: 84, chk_description: "If rehabilitation of PAF is involved", chk_type: "acquisition" },
    { chk_id: 199, chk_description: "Copy of Affidavit sworn by the landowner", chk_type: "emp_prop" },
    { chk_id: 200, chk_description: "Copy of Indemnity Bond executed by the landowner", chk_type: "emp_prop" },
    { chk_id: 201, chk_description: "Whether the name of landowner is recorded in Register-II of State Revenue Department, Jharkhand?", chk_type: "emp_prop" },
    { chk_id: 134, chk_description: "Whether ‘no objection certificate’ from Coal Controller has been issued", chk_type: "acquisition" },
    { chk_id: 167, chk_description: "A statement regarding the PAFs who have received ‘One-time Lump sum amount in lieu of alternative house site that no plot at any rehabilitation site has been allotted to such PAFs", chk_type: "asset_rr" },
    { chk_id: 174, chk_description: "Standard Attestation Form", chk_type: "emp_prop" },
    { chk_id: 175, chk_description: "Copy of the publication in ECL Website regarding purchase/possession of land", chk_type: "emp_prop" },
    { chk_id: 185, chk_description: "A copy of Form-IV (Land possession document)", chk_type: "emp_prop" },
    { chk_id: 187, chk_description: "Land Utilization Certificate to be issued by the Unit Authority in prescribed format (Form - VIII).", chk_type: "emp_prop" },
    { chk_id: 188, chk_description: "Duly filled in & signed Form-IX", chk_type: "emp_prop" },
    { chk_id: 189, chk_description: "Duly filled in & signed Form-X", chk_type: "emp_prop" },
    { chk_id: 191, chk_description: "Copy of the Schedule of land approved by the Competent Authority/ Board of Directors highlighting the plots involved in the instant proposal by washing those in a different color", chk_type: "emp_prop" },
    { chk_id: 192, chk_description: "Copy of the approval of employment approved by the Competent Authority/ Board of Directors", chk_type: "emp_prop" },
    { chk_id: 194, chk_description: "Summary of land offered for the employment (in standard Form-XI)", chk_type: "emp_prop" },
    { chk_id: 195, chk_description: "Gist of the land offered for employment in Form-XII", chk_type: "emp_prop" },
    { chk_id: 203, chk_description: "Copies of Registered deeds/ legal instruments by which nominators obtained ownership of the offered lands", chk_type: "emp_prop" },
    { chk_id: 204, chk_description: "Copy of Form-I submitted by Landowner", chk_type: "emp_prop" },
    { chk_id: 210, chk_description: "Certificate in Form-XVIII (Status of cancellation of Patta)", chk_type: "emp_prop" },
    { chk_id: 211, chk_description: "Affidavit of Patta-holder in standard Format Form-XIX (as per Activity Step 3.3.G)", chk_type: "emp_prop" },
    { chk_id: 212, chk_description: "Agreement with Patta-holder in standard Format Form-XX (as per Activity Step 3.3.F)", chk_type: "emp_prop" },
    { chk_id: 213, chk_description: "Opinion of the Lawyer covering all the matters specified in Activity Step 3.3.B", chk_type: "emp_prop" },
    { chk_id: 214, chk_description: "Copy of Patta Certificates", chk_type: "emp_prop" },
    { chk_id: 10, chk_description: "Whether the Quantum of land to be acquired is within the limit approved in the Project Report/ Scheme/ Conceptual report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 45, chk_description: "Whether the Quantum of land to be acquired is within the limit approved in the Project Report/ Scheme/ Conceptual report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 67, chk_description: "Whether the Quantum of land to be acquired is within the limit approved in the Project Report/ Scheme/ Conceptual report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 19, chk_description: "Involvement of employment, if any (Specify Number of employments and conditional employments)", chk_type: "acquisition" },
    { chk_id: 33, chk_description: "Involvement of employment, if any (Specify Number of employments and conditional employments)", chk_type: "possession" },
    { chk_id: 76, chk_description: "Involvement of employment, if any (Specify Number of employments and conditional employments)", chk_type: "acquisition" },
    { chk_id: 54, chk_description: "Involvement of employment, if any (Specify Number of employments and conditional employments)", chk_type: "acquisition" },
    { chk_id: 40, chk_description: "Report on examination of the proposal by the Area Land Cell Committee and recommendation thereof", chk_type: "possession" },
    { chk_id: 63, chk_description: "Report on examination of the proposal by the Area Land Cell Committee and recommendation thereof", chk_type: "acquisition" },
    { chk_id: 82, chk_description: "Report on examination of the proposal by the Area Land Cell Committee and recommendation thereof", chk_type: "acquisition" },
    { chk_id: 25, chk_description: "Report on examination of the proposal by the Area Land Cell Committee and recommendation thereof", chk_type: "acquisition" },
    { chk_id: 49, chk_description: "Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 14, chk_description: "Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project", chk_type: "acquisition" },
    { chk_id: 27, chk_description: "Copies of relevant pages of approved PR/ Scheme/ Conceptual Report of the Mine/ Project", chk_type: "possession" },
    { chk_id: 48, chk_description: "A revenue plan showing the boundary of the approved/ authorized project/ working area, important surface features, land owned by ECL, Government land, Patta Land, Forest land and area of land to be acquired for the workings as well as other ancillary activities approved for the project/ mine washed in different colors and all details mentioned in Activity step 1.2.A(d)", chk_type: "acquisition" },
    { chk_id: 72, chk_description: "Copies of statutory clearances like approval obtained from DGMS etc., if obtained", chk_type: "acquisition" },
    { chk_id: 109, chk_description: "Whether full or part of the land is included in the Raniganj Master Plan or any such prevalent plan approved by the Central/ State Government for which the concerned title holder is to be rehabilitated under the specific terms and conditions as approved by the Central/ State Government", chk_type: "rr_packg" },
    { chk_id: 96, chk_description: "Number of Project Affected Families (PAFs) to be rehabilitated as per census report", chk_type: "rr_packg" },
    { chk_id: 98, chk_description: "Number of PAFs to be shifted with payment of one-time lump sum monetary compensation as per R&R Policy of CIL", chk_type: "rr_packg" },
    { chk_id: 105, chk_description: "Estimated amount to be paid on account of one-time lumpsum monetary compensation, if any", chk_type: "rr_packg" },
    { chk_id: 89, chk_description: "Whether census for identification of PAFs has been carried out within the time stipulated in Activity Step 8.B of the SOP. If not, a copy of the document showing an explanation for the same.", chk_type: "rr_packg" },
    { chk_id: 92, chk_description: "Whether identified Displaced Families are covered under the provision of approved Scheme/ Project report", chk_type: "rr_packg" },
    { chk_id: 131, chk_description: "Whether the land data has been authenticated by the concerned authorities of District revenue department", chk_type: "acquisition" },
    { chk_id: 121, chk_description: "Filled up standard format of questionnaire duly signed by the Competent Authority (Area General Manager)", chk_type: "acquisition" },
    { chk_id: 118, chk_description: "Filled up standard format of questionnaire duly signed by the Competent Authority (Area General Manager)", chk_type: "acquisition" },
    { chk_id: 137, chk_description: "Filled up standard format of questionnaire duly signed by the Competent Authority (Area General Manager)", chk_type: "acquisition" },
    { chk_id: 141, chk_description: "Filled up standard format of questionnaire duly signed by the Competent Authority (Area General Manager)", chk_type: "acquisition" },
    { chk_id: 124, chk_description: "Detailed plan, as per revenue records with schedule, showing the total area to be notified under section 7(1), in which the area notified under section 4(1) should also be clearly indicated in different colour. The scale of the plan shall be RF 1 : 4000 scale (1 cm = 40 meters). (Five copies of plan to be sent in physical mode)", chk_type: "acquisition" },
    { chk_id: 125, chk_description: "A proposed draft notification under Section 7(1) of the CBA Act in respect of the coal block/ area in English and in Hindi (both hard copy as well as soft copy). (Specimen of the draft notification is given at Format No. 2D).", chk_type: "acquisition" },
    { chk_id: 127, chk_description: "Certificate confirming that the area proposed to be notified has not been leased out to any other person or party by the State Government / Central Government for any other purpose. (Specimen of the certificate is given at Format No. 1B).", chk_type: "acquisition" },
    { chk_id: 115, chk_description: "Certificate confirming that the area proposed to be notified has not been leased out to any other person or party by the State Government / Central Government for any other purpose. (Specimen of the certificate is given at Format No. 1B)", chk_type: "acquisition" },
    { chk_id: 129, chk_description: "Certificate indicating that sufficient coal is available in the area proposed to be notified. A copy of the relevant exploration report may be enclosed. (Specimen of the certificate is given at Format No. 2A)", chk_type: "acquisition" },
    { chk_id: 123, chk_description: "If the prospecting time is extended, then the notification indicating the same may also be submitted.", chk_type: "acquisition" },
    { chk_id: 93, chk_description: "Whether the land to be acquired for the Rehabilitation Site is within Provision of the approved Scheme/ Project report/ approval of the competent authority", chk_type: "rr_packg" },
    { chk_id: 86, chk_description: "In case of non-availability of approved Rehabilitation Planning Guideline, Scheme for Rehabilitation prepared by the concerned Area and recommended by the Area General Manager.", chk_type: "rr_packg" },
    { chk_id: 104, chk_description: "Document that furnishes authentic/ approved SOR/ Rate charts etc which have been considered for valuation of assets", chk_type: "rr_packg" },
    { chk_id: 110, chk_description: "A revenue plan showing existing villages to be shifted and proposed rehabilitation site for the PAFs indicating land owned by ECL, Government Land, Patta land and land proposed to be acquired washed in different colors.", chk_type: "rr_packg" },
    { chk_id: 112, chk_description: "Consent of landowners/villagers at and around the rehabilitation site (Attach minutes of meeting/ agreement etc.)", chk_type: "rr_packg" },
    { chk_id: 166, chk_description: "In case some of the recipients are entitled to get benefits under First and Second Schedule of the RFCTLARR Act, 2013 for lands acquired under the CBA (A&D) Act 1957, but they have been provided R&R benefits as per his choice i.e. R&R Policy of CIL, then mention if the related PAFS have submitted required Affidavits under 108 of the RFCTLARR Act and have signed Agreement with ECL u/s 14(1) of the CBA (A&D) Act 1957. (attach copy)", chk_type: "asset_rr" },
    { chk_id: 148, chk_description: "Details of the schedules and provisions of RFCTLARR Act, 2013 or any other prevalent statute under which the Compensation Payroll has been prepared", chk_type: "compensation" },
    { chk_id: 224, chk_description: "If the Rehabilitation of PAFs is involved then he will take immediate actions as per the approved 'Rehabilitation Planning Guideline' or in the absence of the same for preparation and consent with respect to 'Scheme for Rehabilitation' as described in Activity Step- 8 of the SOP. ", chk_type: "acquisition" },
    { chk_id: 229, chk_description: "Will entrust suitable officials of his Area for collection of data and information regarding ownership of the lands and getting the same authenticated by the concerned authorities of the District revenue department. ", chk_type: "acquisition" },
    { chk_id: 220, chk_description: "Submit all documents like a detailed schedule of plots for acquisition, a Copy of relevant pages of the Project Report/ Scheme, a Copy of the Geological report, and Five copies of Mouza maps showing specified areas in different mouzas that has been proposed for acquisition statements and certificates in prescribed Form 2A, 2B, 2C, 2D etc. and Any other document which will be needed for notification under Section 7 of the Act. (Care should be taken to complete this step as early as possible because the maximum time allowed between notification u/s 4 and 7 is Two Years. Central Government may extend this period up to further one year). \n", chk_type: "acquisition" },
    { chk_id: 225, chk_description: "Publish the content of Notification u/s 7 along with the schedule of land on the website of the company and in two newspapers, one in well-circulated English daily and one in well-circulated local vernacular.", chk_type: "acquisition" },
    { chk_id: 230, chk_description: "Send written requests to General Manager (P&P) and General Manager (Systems) attaching the required plan and other information like latitude/ longitude of the acquired land including the settlements/ villages that lie within the area of acquisition for capturing Satellite images of the same area.", chk_type: "acquisition" },
    { chk_id: 228, chk_description: "Send written requests to General Manager (P&P) and General Manager (Systems) attaching the required plan and other information like latitude/ longitude of the acquired land including the settlements/ villages that lie within the area of acquisition for capturing Satellite images of the same area.", chk_type: "acquisition" },
    { chk_id: 219, chk_description: "Publish the content of Notification u/s 11 along with the schedule of land as notified u/s 9 on the website of the company and in two newspapers, one in well-circulated English daily and one in well-circulated local vernacular.", chk_type: "acquisition" },
    { chk_id: 226, chk_description: "For Rehabilitation of PAFs Area General Manager will also take steps for constitution of the Resettlement & Rehabilitation Committee as described in Activity Step- 8.B.6 of the SOP. ", chk_type: "acquisition" },
    { chk_id: 182, chk_description: "Whether plots offered for employment have been mutated in favour of ECL (except where the land has been acquired through the CBA (A&D) Act, 1957 or where the SPT/CNT Act is applicable).", chk_type: "emp_prop" },
    { chk_id: 217, chk_description: "Mutation document in favour of ECL. Proper justification by the Area Land dealing officer and Area General Manager, if not mutated", chk_type: "emp_prop" },
    { chk_id: 179, chk_description: "Whether all pages of photocopies of documents submitted by the nominee/candidate along with his employment application have been countersigned by him with the date and a Remark, “Submitted by me and is a photocopy of original”.", chk_type: "emp_prop" },
    { chk_id: 181, chk_description: "Whether R.O.Rs of the offered plot (s) have been thoroughly examined and verified by the concerned Revenue Inspector / Amin/land clerk/ surveyor as the case may be mentioning his/ her full name, designation, date", chk_type: "emp_prop" },
    { chk_id: 44, chk_description: "Specific proposal stating purpose, justification and detailing with respect to acquisition of land", chk_type: "acquisition" },
    { chk_id: 9, chk_description: "Specific proposal stating purpose, justification and detailing with respect to\nacquisition of land", chk_type: "acquisition" },
    { chk_id: 66, chk_description: "Specific proposal stating purpose, justification and detailing with respect to acquisition of land", chk_type: "acquisition" },
    { chk_id: 69, chk_description: "Schedule of land in tabular form with land type-wise and mouza-wise abstract", chk_type: "acquisition" },
    { chk_id: 13, chk_description: "A revenue plan showing the boundary of the approved/ authorized project/ working area, important surface features, land owned by ECL, Government land, Patta Land, Forest land and area of land to be acquired for the workings as well as other ancillary activities approved for the project/ mine washed in different colours.", chk_type: "acquisition" },
    { chk_id: 71, chk_description: "A revenue plan showing the boundary of the approved/ authorized project/ working area, important surface features, land owned by ECL, Government land, Patta Land, Forest land and area of land to be acquired for the workings as well as other ancillary activities approved for the project/ mine washed in different colors.", chk_type: "acquisition" },
    { chk_id: 75, chk_description: "A standard Check List as circulated through Office Order (Ref. No. ECL/CMD/LRE/ANG/Check-list/1071 Date 25th Nov 2005)", chk_type: "acquisition" },
    { chk_id: 20, chk_description: "Techno-Economic Report showing estimated total financial involvement and capital involvement for cost of land acquisition, rehabilitation and employment for land", chk_type: "acquisition" },
    { chk_id: 55, chk_description: "Techno-Economic Report showing estimated total financial involvement and capital involvement for cost of land acquisition, rehabilitation and employment for land.", chk_type: "acquisition" },
    { chk_id: 77, chk_description: "Techno-Economic Report showing estimated total financial involvement and capital involvement for cost of land acquisition, rehabilitation and employment for land", chk_type: "acquisition" },
    { chk_id: 22, chk_description: "Documents to substantiate the rates of compensation of Tenancy land like copies of agreement with landowners/ previous settlement of compensation, minutes of meeting with landowners, Government certified market value etc. for current land or chronologically nearest previous case of possession of land", chk_type: "acquisition" },
    { chk_id: 79, chk_description: "Documents to substantiate the rates of compensation of Tenancy land like copies of agreements with landowners/ previous settlement of compensation, minutes of meeting with landowners, Government certified market value etc. for current land or chronologically nearest previous case of possession of land", chk_type: "acquisition" },
    { chk_id: 80, chk_description: "Documents to substantiate the rates of compensation of Government land/ Patta Land like the copy of Government certified market value/ demand of District Authority etc.", chk_type: "acquisition" },
    { chk_id: 24, chk_description: "Documents to substantiate the rates of compensation of Forest land like copies of demands of the State Forest department etc.", chk_type: "acquisition" },
    { chk_id: 29, chk_description: "Schedule of land furnishing details like mouza name, plot no, land type, total area, area already possessed, area for which possession is to be taken, remarks if any", chk_type: "possession" },
    { chk_id: 32, chk_description: "A Revenue plan (mouza plan) showing the concerned land area that is to be possessed along with project boundary and year-wise land utilization plan", chk_type: "possession" },
    { chk_id: 176, chk_description: "Declaration in the form of an Affidavit (solemnized before the First Class Magistrate) submitted by the applicant/ nominee as per Activity Step 4.E", chk_type: "emp_prop" },
    { chk_id: 36, chk_description: "Documents to substantiate the rates of compensation of Tenancy land like copy of agreement with landowners/ previous settlement of compensation, minutes of meeting with landowners, Government certified market value etc.", chk_type: "possession" },
    { chk_id: 37, chk_description: "Documents to substantiate the rates of compensation of Government land/ Patta Land like copy of Government certified market value/ demand of District Authority etc.", chk_type: "possession" },
    { chk_id: 56, chk_description: "Calculation sheet showing the cost of acquisition of all types of land including cost of registration and mutation.", chk_type: "acquisition" },
    { chk_id: 57, chk_description: "Documents to substantiate the rates of compensation of Tenancy land like copies of agreements with landowners etc. for current land or rates approved for similar types of lands in the same/ nearby mine in recent past.", chk_type: "acquisition" },
    { chk_id: 59, chk_description: "Copy of authentic document showing the situation of the project/ mine (For ascertaining the rate of processing fees for mutation)", chk_type: "acquisition" },
    { chk_id: 1, chk_description: "Copy of Notification under section 4", chk_type: "acquisition" },
    { chk_id: 4, chk_description: "Copy of Notification under section 11", chk_type: "acquisition" },
    { chk_id: 113, chk_description: "Copies of plan showing the block area with village boundaries and village schedule to be notified at 1” = 1 miles or 1” = 2 miles scale, considering block size in A3 size paper.", chk_type: "acquisition" },
    { chk_id: 114, chk_description: "Certificate confirming that coal is likely to be found in the area proposed to be notified and the basis of such assumption with documentary evidence/reports etc. (Specimen of the certificate is given at Format No.1A)", chk_type: "acquisition" },
    { chk_id: 117, chk_description: "A proposed draft notification under Section 4(1) of the CBA Act in respect of the coal block/ area in English and in Hindi (both hard copy as well as soft copy). (Specimen of the draft notification, both English and Hindi version is given at Format No. 1D).", chk_type: "acquisition" },
    { chk_id: 135, chk_description: "A proposed draft notification under Section 9(1) of the CBA Act in respect of the coal block/ area in English and in Hindi (both hard copy as well as soft copy). (Specimen of the draft notification is given at Format No . 3A).", chk_type: "acquisition" },
    { chk_id: 177, chk_description: "Declaration in the form of an Affidavit (solemnized before the First Class Magistrate) - submitted by the landowner/ Nominator specifically stating all clauses mentioned in Activity Step 2.I of the SOP", chk_type: "emp_prop" },
    { chk_id: 136, chk_description: "Detailed plan as per revenue records with a schedule showing the total area to be notified under section 9(1), in which the area notified under section 7(1) should also be clearly indicated in different color. The scale of the plan shall be RF 1 : 4000 scale (1 cm = 40 meters). (Five copies of plan to be sent in physical mode)", chk_type: "acquisition" },
    { chk_id: 140, chk_description: "Upload copy of notices regarding content of Notification u/s 11 along with the schedule of land as notified u/s 9 as published on the website of the company and in two newspapers, one in well-circulated English daily and one in well-circulated local vernacular.", chk_type: "acquisition" },
    { chk_id: 146, chk_description: "An Annexure showing calculations related to the determination of the market value of lands, sample calculation for determination of compensation", chk_type: "compensation" },
    { chk_id: 156, chk_description: "An Annexure showing calculations related to the determination of the market value of lands, sample calculation for determination of compensation", chk_type: "asset_rr" },
    { chk_id: 150, chk_description: "A certificate signed by the Surveyor, Land dealing official, Manager, Agent/Project officer, Area Land Dealing Officer, and members of the Area land Cell stating that no compensation has been paid, no R&R benefit and no employment has been provided against the land involved in the proposed compensation payroll earlier.", chk_type: "compensation" },
    { chk_id: 162, chk_description: "A certificate signed by the Surveyor, Land dealing official, Manager, Agent/Project officer, Area Land Dealing Officer, and members of the Area land Cell stating that no compensation has been paid, no R&R benefit and no employment has been provided against the land involved in the proposed compensation payroll earlier.", chk_type: "asset_rr" },
    { chk_id: 155, chk_description: "In case of the acquisition of property under the CBA (A&D) Act 1957, Copies of Sanction Orders published in the Gazette of India under sections 9 and 11 of the said Act.", chk_type: "asset_rr" },
    { chk_id: 160, chk_description: "Copy of the documents showing the rates as per the PWD/ LA Method that has been approved in the R&R package and has been considered for preparation of payroll", chk_type: "asset_rr" },
    { chk_id: 163, chk_description: "Statement that the beneficiaries have never been provided with the asset compensation and other allowances earlier that have been mentioned in the current payroll.", chk_type: "asset_rr" },
    { chk_id: 168, chk_description: "Application by nominee addressing the Head of the Colliery/Project Authority attaching details in Form V", chk_type: "emp_prop" },
    { chk_id: 178, chk_description: "An Indemnity Bond solemnized before a First Class Executive Magistrate to be given by the candidate/ nominee with sureties as per Activity Step 4.G", chk_type: "emp_prop" },
    { chk_id: 184, chk_description: "Certificate duly signed by surveyor, land dealing official, manager and Agent/Project Officer of the Unit mentioning his/ her full name, designation, date and seal stating that the ECL has encumbrance-free possession over the proposed land area in the offered plots.", chk_type: "emp_prop" },
    { chk_id: 190, chk_description: "Mouza Plan dully super-imposed on a mine working plan indicating the offered plots, important surface features duly endorsed by the mine management to be enclosed. Plots should be shown in specific color with proper index.", chk_type: "emp_prop" },
    { chk_id: 193, chk_description: "Copy of the approval of the Area General Manager for possession of land (as obtained in Step 3 of SOP)", chk_type: "emp_prop" },
    { chk_id: 196, chk_description: "Copies of RoRs of ECL showing ownership over the offered plots (where employment is not offered against agreement or land has not been acquired under the CBA (A&D) Act, 1957)", chk_type: "emp_prop" },
    { chk_id: 202, chk_description: "Copies of the latest published Ownership records (RoR) of landowners/ Nominators certified by an authorized officer of the State Revenue Department/ published on the official website of the State Revenue Department", chk_type: "emp_prop" },
    { chk_id: 205, chk_description: "Additional affidavit (solemnized before the First Class Magistrate) submitted by the recorded landowner on the date of Notification u/s 9 of CBA (A&D) Act 1957 with mandatory clauses mentioned in Activity Step 2.J", chk_type: "emp_prop" },
    { chk_id: 206, chk_description: "Affidavit of last transferee/ \"person interested\" of the land with all the mandatory clauses and additional clauses mentioned in Activity Step 2.I", chk_type: "emp_prop" },
    { chk_id: 208, chk_description: "Whether conditions imposed in the approval have been complied with the proposed employment. Attach a certificate signed by the Colliery Surveyor, Manager and Agent in Form XVII (for conditional employment only)?", chk_type: "emp_prop" },
    { chk_id: 216, chk_description: "Approval of employment against the debottar land?", chk_type: "emp_prop" },
    { chk_id: 198, chk_description: "Copy of Agreement between ECL and Landowner (including special clause as per Activity Step 3.2.C)", chk_type: "emp_prop" },
    { chk_id: 197, chk_description: "Is the CNT Act applicable and employment is offered against Agreement before purchase of land through registration of Deed?", chk_type: "emp_prop" }
  ]

  for (const chk of checks) {
    await db.chk_master_new.upsert({
      where: { chk_id: chk.chk_id },
      update: {
        chk_description: chk.chk_description,
        chk_type: chk.chk_type,
      },
      create: chk,
    })
  }
}
