import type { PrismaClient } from '@prisma/client'

export async function seedWorkflowTransitions(db: PrismaClient) {
  console.log('🌱 Seeding workflow_transitions for Base & Direct Purchase (DP) Land Acquisition...')

  const transitions = [
    // ════════════════════════════════════════════════════════════════════════════
    // 1. BASE LAND_SCHEDULE TRANSITIONS
    // ════════════════════════════════════════════════════════════════════════════
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'submit_to_unit',
      label: 'Submit for Unit Title Search & Survey',
      from_state: 'Drafting',
      to_state: 'UnitSubmitted',
      required_role: 'unit_office',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 10,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'forward_for_cross_colliery',
      label: 'Forward for Cross-Colliery Verification & Form-VII',
      from_state: 'UnitSubmitted',
      to_state: 'CrossCollieryVerification',
      required_role: 'unit_office',
      routing_type: 'MULTI_TARGET',
      target_options_source: 'adjacent_mine_cds',
      guard_key: null,
      sort_order: 15,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'return_to_unit_from_cross_colliery',
      label: 'Reject / Return to Unit (Plot Overlap Found)',
      from_state: 'CrossCollieryVerification',
      to_state: 'UnitSubmitted',
      required_role: 'adjacent_mine_office',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 17,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'submit_to_area',
      label: 'Submit to Area Office for Vetting',
      from_state: 'CrossCollieryVerification',
      to_state: 'AreaVetting',
      required_role: 'unit_office',
      routing_type: 'FORCED',
      guard_key: 'checklist_fully_satisfied',
      sort_order: 20,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'submit_to_hq_parallel',
      label: 'Forward to HQ Parallel Vetting',
      from_state: 'AreaVetting',
      to_state: 'HqParallelVetting',
      required_role: 'area_office',
      routing_type: 'FORCED',
      guard_key: 'within_project_baseline',
      sort_order: 30,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'escalate_to_board',
      label: 'Escalate to Board (Baseline Breached)',
      from_state: 'AreaVetting',
      to_state: 'BoardEscalation',
      required_role: 'area_office',
      routing_type: 'FORCED',
      guard_key: 'baseline_breached',
      sort_order: 35,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'advance_to_gmlre',
      label: 'Consolidate & Pass to GM LRE',
      from_state: 'HqParallelVetting',
      to_state: 'GmLreReview',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: 'parallel_reviews_completed',
      sort_order: 40,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'resolve_escalation',
      label: 'Resolve Board Escalation → GM LRE',
      from_state: 'BoardEscalation',
      to_state: 'GmLreReview',
      required_role: 'board',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 45,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'issue_docket',
      label: 'Issue Proposal Docket',
      from_state: 'GmLreReview',
      to_state: 'DocketIssued',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 50,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'approve_manually',
      label: 'Execute Manual Approval',
      from_state: 'DocketIssued',
      to_state: 'ManuallyApproved',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 55,
    },
    {
      workflow_code: 'LAND_SCHEDULE',
      transition_name: 'publish',
      label: 'Publish Award to Form-D Ledger',
      from_state: 'ManuallyApproved',
      to_state: 'Published',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 60,
    },

    // ════════════════════════════════════════════════════════════════════════════
    // 2. DIRECT PURCHASE (DP) MODE WORKFLOW TRANSITIONS (acq_mode_id = 6)
    // ════════════════════════════════════════════════════════════════════════════
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'submit_to_unit_dp',
      label: 'Submit for Unit Title Search & Survey',
      from_state: 'Drafting',
      to_state: 'UnitSubmitted',
      required_role: 'unit_office',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 10,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'forward_for_cross_colliery_dp',
      label: 'Forward for Cross-Colliery Boundary & Form-VII Vetting',
      from_state: 'UnitSubmitted',
      to_state: 'CrossCollieryVerification',
      required_role: 'unit_office',
      routing_type: 'USER_CHOICE',
      target_options_source: 'adjacent_mine_units',
      guard_key: null,
      sort_order: 20,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'submit_to_area_dp',
      label: 'Submit to Area Office for Vetting (Form-VII Signed)',
      from_state: 'CrossCollieryVerification',
      to_state: 'AreaVetting',
      required_role: 'unit_office',
      routing_type: 'FORCED',
      guard_key: 'checklist_fully_satisfied',
      sort_order: 30,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'submit_to_hq_parallel_dp',
      label: 'Forward to HQ Parallel Vetting (Planning, Finance, Legal)',
      from_state: 'AreaVetting',
      to_state: 'HqParallelVetting',
      required_role: 'area_office',
      routing_type: 'FORCED',
      guard_key: 'within_project_baseline',
      sort_order: 40,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'escalate_to_board_dp',
      label: 'Escalate to Board (Baseline Breached)',
      from_state: 'AreaVetting',
      to_state: 'BoardEscalation',
      required_role: 'area_office',
      routing_type: 'FORCED',
      guard_key: 'baseline_breached',
      sort_order: 45,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'advance_to_gmlre_dp',
      label: 'Consolidate Form-VII & Pass to GM LRE',
      from_state: 'HqParallelVetting',
      to_state: 'GmLreReview',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: 'parallel_reviews_completed',
      sort_order: 50,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'resolve_escalation_dp',
      label: 'Resolve Board Escalation → GM LRE',
      from_state: 'BoardEscalation',
      to_state: 'GmLreReview',
      required_role: 'board',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 55,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'issue_purchase_docket',
      label: 'Issue Direct Purchase Agreement Docket',
      from_state: 'GmLreReview',
      to_state: 'DocketIssued',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 60,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'execute_sale_deed',
      label: 'Execute Sale Deed Sign-off & Payment Clearance',
      from_state: 'DocketIssued',
      to_state: 'ManuallyApproved',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 70,
    },
    {
      workflow_code: 'LAND_SCHEDULE_6',
      transition_name: 'publish_registered_deed',
      label: 'Publish Registered Sale Deed to Form-D Ledger',
      from_state: 'ManuallyApproved',
      to_state: 'Published',
      required_role: 'gm_lre',
      routing_type: 'FORCED',
      guard_key: null,
      sort_order: 80,
    },
  ]

  for (const tr of transitions) {
    await (db as any).workflow_transitions.upsert({
      where: {
        workflow_code_transition_name: {
          workflow_code: tr.workflow_code,
          transition_name: tr.transition_name,
        },
      },
      create: {
        ...tr,
        is_active: true,
        entry_by: 'system',
        updt_by: 'system',
      },
      update: {
        label: tr.label,
        from_state: tr.from_state,
        to_state: tr.to_state,
        required_role: tr.required_role,
        routing_type: tr.routing_type,
        target_options_source: tr.target_options_source ?? null,
        guard_key: tr.guard_key,
        sort_order: tr.sort_order,
        is_active: true,
        updt_by: 'system',
      },
    })
  }

  console.log(`✅ Seeded ${transitions.length} workflow_transitions for Base & Direct Purchase (DP) modes.`)
}
